(function(){
  'use strict';
  const path=location.pathname.toLowerCase();
  const industry=path.includes('/healthcare/')?'healthcare':path.includes('/edtech/')?'edtech':path.includes('/realestate/')?'realestate':path.includes('/bfsi/')?'bfsi':path.includes('/ecommerce/')?'ecommerce':path.includes('/hospitality/')?'hospitality':'';
  if(!industry)return;
  const configs={
    healthcare:[
      ['CarePlus Hospitals','careplushospitals.com','✚','Expert Care, When You Need It','Find the right specialist and book trusted care close to you.','Find a Doctor','Book Appointment',['Cardiology','Orthopaedics','Dermatology','General Medicine'],'Patient Assistant','Hi 👋 I can help you find a doctor and book an appointment.','#087f73','#eaf8f5','../../assets/healthcare/careplus-doctors.jpg'],
      ['CarePlus Patient Portal','careplushospitals.com','📅','Manage Your Appointments','View upcoming visits, make changes and stay connected with your care team.','Upcoming: Dr. Ananya Menon · 14 Aug','View Appointment',['View','Reschedule','Cancel','Get Help'],'Appointment Assistant','Hi 👋 I can help you manage an existing appointment.','#087f73','#eef8f7',''],
      ['CarePlus Diagnostics','careplushospitals.com','🧪','Book Tests & Health Checkups','Convenient diagnostics, preventive packages and home collection support.','Search tests or packages','Search',['CBC','Thyroid','HbA1c','Health Packages'],'Diagnostics Assistant','Hi 👋 I can help you book tests and health checkups.','#1769aa','#eef6fc','../../assets/healthcare/careplus-locations.jpg'],
      ['CarePlus Patient Portal','careplushospitals.com','📋','Reports & Doctor Follow-up','Access recent reports and coordinate the next step in your care.','Search reports','View Reports',['Reports','Recent Tests','Doctor Follow-up','Care Team'],'Patient Assistant','Hi 👋 I can help with reports and follow-up care.','#087f73','#edf8f5',''],
      ['CarePlus Pharmacy','careplushospitals.com','💊','Hospital Pharmacy & Prescription Services','Manage prescription refills and pharmacy orders from one secure place.','Enter prescription or order ID','Continue',['Refill Prescription','Upload Prescription','Track Order','Pharmacy Help'],'Pharmacy Assistant','Hi 👋 I can help with prescriptions and pharmacy services.','#4a6b3f','#f1f7ed',''],
      ['CarePlus Hospitals','careplushospitals.com','♡','Tell Us About Your Experience','Your feedback helps us make every patient interaction more caring.','Share your visit experience','Give Feedback',['Doctor Visit','Hospital Stay','Diagnostics','Support'],'Patient Experience Assistant','Hi 👋 I can help you share feedback about your experience.','#a43c62','#fbedf3','']
    ],
    edtech:[
      ['Northbridge University','northbridgeuniversity.edu','🎓','Build Your Future With Us','Explore career-ready programmes, a vibrant campus and an education built around your goals.','What would you like to study?','Find Programmes',['Engineering','Business','Commerce','Computer Applications'],'Admissions Assistant','Hi 👋 I can help you discover programmes and apply.','#244c92','#edf3fc',''],
      ['Northbridge Applicant Portal','northbridgeuniversity.edu','📝','Your Application, All in One Place','Track progress, complete documents and stay ahead of important deadlines.','Enter application ID','Check Status',['Application Status','Documents','Deadlines','Admissions Help'],'Admissions Desk','Hi 👋 I can help with your application and status.','#244c92','#eef3fb',''],
      ['Northbridge Events','northbridgeuniversity.edu','📣','Discover What’s Happening at Northbridge','Meet faculty, explore programmes and experience our community.','Search events','Explore',['Webinars','Open House','Campus Events','Student Sessions'],'University Updates','Hi 👋 I can help you find and register for university events.','#6a3da5','#f4effb',''],
      ['Northbridge Admissions','northbridgeuniversity.edu','🧭','Plan Your Campus Experience','Speak with an admissions expert or discover campus in person.','Choose a counselling option','Book',['Phone Counselling','Video Counselling','Campus Visit','Ask Admissions'],'Admissions Counsellor','Hi 👋 I can help you book counselling or a campus visit.','#176c7c','#edf7f8',''],
      ['Northbridge Applicant Portal','northbridgeuniversity.edu','✓','Complete Your Application','You’re almost there. Finish the remaining steps to submit your application.','Documents pending','Continue Application',['Personal Details ✓','Programme Selected ✓','Documents Pending','Get Help'],'Admissions Assistant','Hi 👋 I can help you complete your application.','#244c92','#eef3fb','']
    ],
    realestate:[
      ['Aurelia Homes','aureliahomes.com','⌂','Find a Home That Fits Your Life','Explore thoughtfully designed residences in the city’s most connected neighbourhoods.','City · Configuration · Budget','Search Homes',['New Launches','2 & 3 BHK Homes','Premium Residences','Featured Projects'],'Property Assistant','Hi 👋 I can help you discover the right property.','#7b5b36','#f7f2ea',''],
      ['Aurelia Homes','aureliahomes.com','🏙','Explore Your Next Address','Review homes, amenities, floor plans and location advantages before your visit.','Aurelia Heights · From ₹1.4 Cr','Schedule Site Visit',['Configurations','Amenities','Floor Plans','Location'],'Project Advisor','Hi 👋 I can help you explore this project and schedule a visit.','#765338','#f7f1ea',''],
      ['Aurelia Grove','aureliahomes.com','🌿','Introducing Aurelia Grove','A nature-inspired collection of refined 2 & 3 BHK residences.','Launching Soon','Register Interest',['2 BHK Homes','3 BHK Homes','Early Access','Project Preview'],'Launch Assistant','Hi 👋 I can help you register interest in our new launch.','#426b4b','#edf6ee',''],
      ['Aurelia Sales Desk','aureliahomes.com','🤝','Connect With Aurelia Sales','Fast assistance for buyer enquiries, partners and callback requests.','How can we help?','Request Callback',['Buyer Enquiry','Channel Partner','Request Callback','Sales Support'],'Sales Assistant','Hi 👋 I can help with buyer and channel-partner enquiries.','#7b5b36','#f7f2ea',''],
      ['Aurelia Customer Portal','aureliahomes.com','🔑','Your Home, Your Updates','Keep track of payments, construction milestones and important documents.','Enter customer ID','Open Portal',['Property','Payment Schedule','Construction Status','Documents'],'Buyer Support','Hi 👋 I can help with your property and payment updates.','#315e73','#edf5f8',''],
      ['Aurelia Resident Services','aureliahomes.com','🛠','Resident Services, Made Simple','Raise and track service requests for your Aurelia community.','Describe your request','Raise Request',['Raise Request','Track Request','Common Services','Emergency Help'],'Service Assistant','Hi 👋 I can help you raise or track a service request.','#426b4b','#edf6ee','']
    ],
    bfsi:[
      ['SecureSure Insurance','securesure.com','🛡','Protection for Every Journey','Simple coverage for your health, travels and everything you value.','What would you like to protect?','Explore Plans',['Motor','Health','Travel','Life'],'Insurance Assistant','Hi 👋 I can help you discover the right insurance policy.','#156b68','#edf8f6',''],
      ['SecureSure Policy Portal','securesure.com','📄','Your Policies, Always Within Reach','Review coverage, renew policies and download important documents.','Enter policy number','View Policy',['Active Policies','Renewals','Documents','Get Support'],'Policy Assistant','Hi 👋 I can help with renewals and policy documents.','#156b68','#edf8f6',''],
      ['SecureSure Claims','securesure.com','🧰','Claims Support When It Matters','Register, track and get assistance through every step of a claim.','Policy or claim number','Continue',['Register Claim','Track Claim','Cashless Network','Roadside Assistance'],'Claims Assistant','Hi 👋 I can help you register or track a claim.','#8c3d32','#fbefed',''],
      ['Northstar Bank','northstarbank.com','★','Everyday Banking, Made Clear','Manage accounts and service requests securely from one place.','What can we help with?','Get Started',['Accounts','Statements','Service Requests','ATM / Branch'],'Banking Assistant','Hi 👋 I can help with your banking service request.','#174d84','#edf4fb',''],
      ['Northstar Cards','northstarbank.com','💳','Stay in Control of Your Cards','Review transactions and manage card settings in a few simple steps.','•••• 4821 · Platinum Card','Manage Card',['Manage Card','Report Lost','Transactions','Card Controls'],'Card Support','Hi 👋 I can help with your card or transactions.','#174d84','#edf4fb',''],
      ['Northstar Loans','northstarbank.com','↗','Finance Your Next Goal','Explore flexible finance for the moments that move life forward.','How much would you like to borrow?','Check Options',['Personal Loan','Home Loan','Auto Loan','Business Loan'],'Loan Assistant','Hi 👋 I can help you explore loan options and apply.','#5e3d91','#f4effa','']
    ],
    ecommerce:[
      ['Vera Store','shopvera.com','V','New Season. New Favourites.','Discover everyday style, smart essentials and offers curated for you.','Search products','Search',['Fashion','Footwear','Electronics','Home'],'Shopping Assistant','Hi 👋 I can help you find the right product.','#8b3158','#fbeff5','../../assets/ecommerce/running-shoes-catalog.png'],
      ['Vera Store','shopvera.com','V','Your Cart','Your saved picks are ready when you are. Complete checkout securely.','2 items · ₹4,798','Proceed to Checkout',['Saved Cart','Delivery','Offers','Secure Checkout'],'Shopping Assistant','Hi 👋 I can help you continue your saved cart.','#8b3158','#fbeff5',''],
      ['Vera Orders','shopvera.com','📦','Track Your Order','See the latest delivery updates for your Vera Store purchase.','Enter order ID','Track Order',['Order Confirmed','Packed','Shipped','Delivered'],'Order Assistant','Hi 👋 I can help you track your order and delivery.','#31688b','#eef6fb',''],
      ['Vera Orders','shopvera.com','✓','Confirm Your COD Order','Review your order and confirm how you would like to pay.','COD Order · ₹2,499','Confirm Order',['Order Summary','Confirm Order','Payment Method','Need Help'],'Order Assistant','Hi 👋 I can help confirm your COD order.','#8b3158','#fbeff5',''],
      ['Vera Returns','shopvera.com','↺','Returns & Exchanges','Find an order and choose the return, exchange or refund option you need.','Enter order ID','Find Order',['Start Return','Exchange','Refund Status','Return Policy'],'Returns Assistant','Hi 👋 I can help with a return, exchange or refund.','#7b4934','#faf1ec',''],
      ['Vera Help Centre','shopvera.com','?','How Can We Help?','Quick answers and friendly support for every part of your shopping experience.','Search help topics','Search',['Product Help','Orders','Warranty','Shipping & Returns'],'Store Support Assistant','Hi 👋 I can help answer product and order questions.','#315c83','#eef5fa','']
    ],
    hospitality:[
      ['Solene Hotels & Resorts','solenehotels.com','S','Stay Somewhere Remarkable','Discover refined stays, thoughtful service and memorable city experiences.','Where would you like to stay?','Find a Stay',['Beach Escapes','City Hotels','Suites','Special Offers'],'Reservations Assistant','Hi 👋 I can help you find and book the perfect stay.','#0d7770','#eaf7f6','../../assets/hospitality/grand-club-room.png'],
      ['Solene Dining','solenehotels.com','S','A Table for Every Occasion','Explore signature restaurants and reserve your preferred dining experience.','Restaurant or cuisine','Find a Table',['Signature Dining','All-day Dining','Rooftop','Private Dining'],'Dining Assistant','Hi 👋 I can help you reserve a restaurant table.','#8b4d37','#faf0eb',''],
      ['Solene Concierge','solenehotels.com','S','Your Stay, Thoughtfully Managed','Request hotel services and discover everything available during your stay.','How can we help?','Request Service',['Room Service','Housekeeping','Transport','Local Guide'],'Guest Services Assistant','Hi 👋 I can help with guest services and concierge requests.','#6b4f88','#f4eff8',''],
      ['Solene Journeys','solenehotels.com','S','Discover More of the World','Explore curated tour packages shaped around how you want to travel.','Where do you want to go?','Explore Tours',['Nature','Culture','Adventure','Family'],'Travel Sales Assistant','Hi 👋 I can help you discover the right tour package.','#176b67','#eaf7f6',''],
      ['Solene Journeys','solenehotels.com','S','Plan Every Detail With Confidence','Explore itineraries, inclusions and departure information with expert support.','Search a tour','View Details',['Itineraries','Departures','Inclusions','Travel Advisor'],'Travel Advisor','Hi 👋 I can help with tour details and travel planning.','#176b67','#eaf7f6',''],
      ['Solene Support','solenehotels.com','S','We’re Here to Help','Get assistance with an existing hotel or tour reservation.','Booking or enquiry ID','Get Support',['Modify Booking','Cancellation','FAQs','Talk to Support'],'Booking Support','Hi 👋 I can help with your booking or enquiry.','#8b3158','#fbeff5','']
    ]
  };
  const systems={
    healthcare:{name:'CarePlus Hospitals',domain:'careplushospitals.com',mark:'CP',accent:'#087F73',ink:'#123B42',soft:'#F3FAF8',nav:['Find a Doctor','Specialities','Hospitals','Appointments','Health Checkups','Contact'],bot:'CarePlus Assistant',trust:['Trusted specialists','24/7 patient support','Secure patient journeys'],images:['doctor-consultation.webp','medical-team.webp','diagnostics-care.webp','doctor-consultation.webp','diagnostics-care.webp','medical-team.webp']},
    edtech:{name:'Northbridge University',domain:'northbridgeuniversity.edu',mark:'N',accent:'#4356B2',ink:'#27346D',soft:'#F1F2FA',nav:['Programs','Admissions','Fees & Scholarships','Campus','Student Life','Contact'],bot:'Northbridge Admissions',trust:['Career-ready programmes','Scholarship support','A vibrant campus'],images:['campus-building.webp','students-collaborating.webp','campus-life.webp','campus-building.webp','students-collaborating.webp']},
    realestate:{name:'Aurelia Homes',domain:'aureliahomes.com',mark:'A',accent:'#80907C',ink:'#282B29',soft:'#F8F6F1',nav:['Projects','Locations','New Launches','About','Contact'],bot:'Aurelia Property Assistant',trust:['Design-led homes','Prime locations','Dedicated advisors'],images:['residential-exterior.webp','luxury-interior.webp','project-architecture.webp','residential-exterior.webp','luxury-interior.webp','project-architecture.webp']},
    bfsi:{name:'Northstar Financial',domain:'northstarfinancial.com',mark:'N',accent:'#176BCE',ink:'#102A43',soft:'#EEF5FA',nav:['Banking','Insurance','Cards','Loans','Claims','Support'],bot:'Northstar Assistant',trust:['Secure by design','Banking & protection','Guided digital service'],images:['financial-planning.webp','customer-advisor.webp','customer-advisor.webp','financial-planning.webp','savings-growth.webp','savings-growth.webp']},
    ecommerce:{name:'Vera',domain:'shopvera.com',mark:'V',accent:'#D96856',ink:'#202020',soft:'#F7F3EC',nav:['New In','Women','Men','Footwear','Home','Offers'],bot:'Vera Shopping Assistant',trust:['Curated essentials','Easy delivery','Simple returns'],images:['fashion-editorial.webp','seasonal-fashion.webp','product-footwear.webp','fashion-editorial.webp','seasonal-fashion.webp','product-footwear.webp']},
    hospitality:{name:'Solene',domain:'solene.com',mark:'S',accent:'#7B2638',ink:'#282522',soft:'#FBF8F3',nav:['Hotels','Dining','Experiences','Journeys','Offers','Support'],bot:'Solene Assistant',trust:['Remarkable stays','Curated journeys','Thoughtful service'],images:['resort-hero.webp','fine-dining.webp','resort-hero.webp','travel-landscape.webp','travel-landscape.webp','resort-hero.webp']}
  };
  const root=document.getElementById('modalRoot'),overlay=document.getElementById('modalOverlay');
  if(!root||!overlay)return;
  root.classList.add('webchat-enhanced');
  let flow=0,channel='wa',autoTimer=0;
  const toolbar=root.querySelector('.demo-toolbar,.mode-bar');
  let channelBar=root.querySelector('.chan-toggle');
  if(channelBar){channelBar.classList.add('web-channel-switch');channelBar.querySelectorAll('button').forEach((b,i)=>{b.classList.add('web-channel-btn');b.dataset.channel=i?'web':'wa';if(!b.querySelector('.web-channel-dot'))b.insertAdjacentHTML('afterbegin','<span class="web-channel-dot"></span>');});}
  else{channelBar=document.createElement('div');channelBar.className='web-channel-switch';channelBar.innerHTML='<button class="web-channel-btn active" type="button" data-channel="wa"><span class="web-channel-dot"></span>WhatsApp</button><button class="web-channel-btn" type="button" data-channel="web"><span class="web-channel-dot"></span>Website Chat</button>';toolbar.insertAdjacentElement('afterend',channelBar);}
  const stage=document.createElement('div');stage.className='web-demo-stage';stage.setAttribute('aria-hidden','true');
  const widget=document.createElement('div');widget.className='web-demo-widget';
  const header=root.querySelector('.mh,.modal-header'),steps=root.querySelector('.steps-bar'),chat=root.querySelector('.chat-area'),quick=root.querySelector('.qr'),footer=root.querySelector('.mfooter,.modal-footer');
  [header,steps,chat,quick,footer].forEach(el=>{if(el)widget.appendChild(el)});root.append(stage,widget);
  const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function cfg(){const list=configs[industry]||configs.hospitality,base=[...(list[Math.min(flow,list.length-1)]||list[0])],system=systems[industry]||systems.hospitality;base[0]=system.name;base[1]=system.domain;base[2]=system.mark;base[11]=system.accent;base[12]=system.soft;base[13]=`../../assets/website-previews/${industry}/${system.images[flow%system.images.length]}`;base.system=system;return base}
  function renderSite(){const c=cfg(),s=c.system,hero=c[13],cards=s.images.filter(x=>x!==s.images[flow%s.images.length]);root.style.setProperty('--web-accent',s.accent);root.style.setProperty('--web-ink',s.ink);root.style.setProperty('--web-soft',s.soft);stage.innerHTML=`<div class="web-demo-browser"><i></i><i></i><i></i><span class="web-demo-address">🔒 ${e(s.domain)}</span></div><div class="web-demo-site" style="--site-accent:${e(s.accent)};--site-ink:${e(s.ink)};--site-soft:${e(s.soft)}"><div class="web-site-nav"><div class="web-site-brand"><span class="web-site-mark">${e(s.mark)}</span>${e(s.name)}</div><div class="web-site-links">${s.nav.map(x=>`<span>${e(x)}</span>`).join('')}<span class="web-site-nav-cta">${e(c[6])}</span></div></div><section class="web-site-hero"><div class="web-site-copy"><span class="web-site-kicker">${e(s.name)}</span><h2>${e(c[3])}</h2><p>${e(c[4])}</p><div class="web-site-action"><div class="web-site-search">${e(c[5])}</div><button class="web-site-button" type="button">${e(c[6])}</button></div></div><div class="web-site-hero-media"><img src="${e(hero)}" alt="" loading="eager"><div class="web-site-float"><strong>${e(c[7][0])}</strong><small>${e(c[6])} →</small></div></div></section><div class="web-site-trust">${s.trust.map((x,i)=>`<span>${i===0?'<b>✦</b>':''}${e(x)}</span>`).join('')}</div><div class="web-site-cards">${c[7].map((x,i)=>`<div class="web-site-card"><img src="../../assets/website-previews/${e(industry)}/${e(cards[i%cards.length])}" alt="" loading="lazy"><div><strong>${e(x)}</strong><small>Explore ${e(s.name)} <b>→</b></small></div></div>`).join('')}</div><div class="web-demo-greeting">Need help? Ask our AI Assistant.</div><button class="web-demo-launcher" type="button" aria-label="Open AI Assistant"><span aria-hidden="true">✦</span></button></div>`;stage.setAttribute('aria-hidden','false');stage.querySelector('.web-demo-launcher').addEventListener('click',openWidget);}
  function isText(){return root.dataset.mode==='text'||document.getElementById('textModeBtn')?.classList.contains('active')}
  function restart(){const b=document.getElementById('restartBtn')||root.querySelector('.rst-btn');if(b)b.click()}
  function applyWebBrand(){if(channel!=='web')return;const s=cfg().system,title=document.getElementById('modalTitle'),sub=document.getElementById('modalSub'),avatar=document.getElementById('modalAvatar'),input=document.getElementById('chatInput');if(title)title.textContent=s.bot;if(sub)sub.textContent='● Online';if(avatar)avatar.textContent=s.mark;if(input)input.placeholder='Ask me anything…';if(header)header.style.background=s.accent}
  function openWidget(){clearTimeout(autoTimer);root.classList.add('web-widget-open');restart();setTimeout(applyWebBrand,0)}
  function closeWidget(){root.classList.remove('web-widget-open')}
  function scheduleAuto(){clearTimeout(autoTimer);if(channel==='web'&&isText())autoTimer=setTimeout(()=>{const l=stage.querySelector('.web-demo-launcher');if(l)l.classList.add('pulse');setTimeout(openWidget,450)},1050)}
  function selectChannel(next,reset=true){channel=next;clearTimeout(autoTimer);channelBar.querySelectorAll('[data-channel]').forEach(b=>b.classList.toggle('active',b.dataset.channel===next));root.classList.toggle('web-channel',next==='web');closeWidget();if(next==='web'){renderSite();scheduleAuto()}else{stage.setAttribute('aria-hidden','true');if(reset)restart()}}
  channelBar.addEventListener('click',ev=>{const b=ev.target.closest('[data-channel]');if(!b||b.dataset.channel===channel)return;selectChannel(b.dataset.channel)});
  document.addEventListener('click',ev=>{const opener=ev.target.closest('[data-open-flow]');if(opener){flow=Number(opener.dataset.openFlow)||0;setTimeout(()=>selectChannel('wa',false),0)}},false);
  document.getElementById('textModeBtn')?.addEventListener('click',()=>setTimeout(()=>{if(channel==='web'){closeWidget();scheduleAuto()}},0));
  document.getElementById('structuredModeBtn')?.addEventListener('click',()=>setTimeout(()=>{if(channel==='web'){clearTimeout(autoTimer);closeWidget()}},0));
  document.getElementById('langSelect')?.addEventListener('change',()=>setTimeout(applyWebBrand,0));
  document.getElementById('languageSelect')?.addEventListener('change',()=>setTimeout(applyWebBrand,0));
  (document.getElementById('restartBtn')||root.querySelector('.rst-btn'))?.addEventListener('click',()=>setTimeout(applyWebBrand,0));
  document.getElementById('closeModalBtn')?.addEventListener('click',()=>{clearTimeout(autoTimer);selectChannel('wa',false)});
  overlay.addEventListener('click',ev=>{if(ev.target===overlay){clearTimeout(autoTimer);selectChannel('wa',false)}});
  if(industry==='hospitality'){
    document.addEventListener('click',ev=>{const direct=ev.target.closest('[onclick]');if(direct&&direct.getAttribute('onclick').includes('openFlow(')){const m=direct.getAttribute('onclick').match(/openFlow\((\d+)/);if(m){flow=Number(m[1]);setTimeout(()=>selectChannel('wa',false),0)}}});
  }
})();
